begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|exist
package|;
end_package

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|dom
operator|.
name|QName
import|;
end_import

begin_comment
comment|/**  * Global namespace declarations.  *   * @author wolf  *  */
end_comment

begin_interface
specifier|public
interface|interface
name|Namespaces
block|{
specifier|public
specifier|final
specifier|static
name|String
name|SCHEMA_NS
init|=
literal|"http://www.w3.org/2001/XMLSchema"
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|SCHEMA_DATATYPES_NS
init|=
literal|"http://www.w3.org/2001/XMLSchema-datatypes"
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|SCHEMA_INSTANCE_NS
init|=
literal|"http://www.w3.org/2001/XMLSchema-instance"
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|XPATH_DATATYPES_NS
init|=
literal|"http://www.w3.org/2003/05/xpath-datatypes"
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|EXIST_NS
init|=
literal|"http://exist.sourceforge.net/NS/exist"
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|XML_NS
init|=
literal|"http://www.w3.org/XML/1998/namespace"
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|XMLNS_NS
init|=
literal|"http://www.w3.org/2000/xmlns/"
decl_stmt|;
comment|/** QName representing xml:id */
specifier|public
specifier|final
specifier|static
name|QName
name|XML_ID_QNAME
init|=
operator|new
name|QName
argument_list|(
literal|"id"
argument_list|,
name|XML_NS
argument_list|,
literal|"xml"
argument_list|)
decl_stmt|;
comment|/** QName representing xml:space */
specifier|public
specifier|final
specifier|static
name|QName
name|XML_SPACE_QNAME
init|=
operator|new
name|QName
argument_list|(
literal|"space"
argument_list|,
name|XML_NS
argument_list|,
literal|"xml"
argument_list|)
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|SOAP_ENVELOPE
init|=
literal|"http://schemas.xmlsoap.org/soap/envelope/"
decl_stmt|;
comment|//SAXfeatures / properties : move toadedicated package
specifier|public
specifier|final
specifier|static
name|String
name|SAX_LEXICAL_HANDLER
init|=
literal|"http://xml.org/sax/properties/lexical-handler"
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|SAX_NAMESPACES
init|=
literal|"http://xml.org/sax/features/namespaces"
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|SAX_NAMESPACES_PREFIXES
init|=
literal|"http://xml.org/sax/features/namespace-prefixes"
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|SAX_VALIDATION
init|=
literal|"http://xml.org/sax/features/validation"
decl_stmt|;
specifier|public
specifier|final
specifier|static
name|String
name|SAX_VALIDATION_DYNAMIC
init|=
literal|"http://apache.org/xml/features/validation/dynamic"
decl_stmt|;
block|}
end_interface

end_unit

