begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * eXist Open Source Native XML Database  * Copyright (C) 2008-2012 The eXist Project  * http://exist-db.org  *  * This program is free software; you can redistribute it and/or  * modify it under the terms of the GNU Lesser General Public License  * as published by the Free Software Foundation; either version 2  * of the License, or (at your option) any later version.  *    * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU Lesser General Public License for more details.  *  * You should have received a copy of the GNU Lesser General Public License  * along with this program; if not, write to the Free Software Foundation  * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.  *    *  $Id$  */
end_comment

begin_package
package|package
name|org
operator|.
name|exist
operator|.
name|config
package|;
end_package

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|Database
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|dom
operator|.
name|DocumentAtExist
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|dom
operator|.
name|NodeAtExist
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|xmldb
operator|.
name|XmldbURI
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|*
import|;
end_import

begin_comment
comment|/**  * Document proxy object. Help to provide single interface for in-memory& store documents.  *   * @author<a href="mailto:shabanovd@gmail.com">Dmitriy Shabanov</a>  *  */
end_comment

begin_class
specifier|public
class|class
name|ProxyDocument
parameter_list|<
name|E
extends|extends
name|DocumentAtExist
parameter_list|>
extends|extends
name|ProxyNode
argument_list|<
name|E
argument_list|>
implements|implements
name|DocumentAtExist
block|{
specifier|private
name|E
name|document
decl_stmt|;
specifier|public
name|Database
name|getDatabase
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getDatabase
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.exist.i.dom.DocumentAtExist#getFirstChildFor(int) 	 */
specifier|public
name|int
name|getFirstChildFor
parameter_list|(
name|int
name|nodeNumber
parameter_list|)
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getFirstChildFor
argument_list|(
name|nodeNumber
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.exist.i.dom.DocumentAtExist#getNextNodeNumber(int) 	 */
specifier|public
name|int
name|getNextNodeNumber
parameter_list|(
name|int
name|nodeNr
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getNextNodeNumber
argument_list|(
name|nodeNr
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#adoptNode(org.w3c.dom.Node) 	 */
specifier|public
name|Node
name|adoptNode
parameter_list|(
name|Node
name|source
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|adoptNode
argument_list|(
name|source
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#createAttribute(java.lang.String) 	 */
specifier|public
name|Attr
name|createAttribute
parameter_list|(
name|String
name|name
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|createAttribute
argument_list|(
name|name
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#createAttributeNS(java.lang.String, java.lang.String) 	 */
specifier|public
name|Attr
name|createAttributeNS
parameter_list|(
name|String
name|namespaceURI
parameter_list|,
name|String
name|qualifiedName
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|createAttributeNS
argument_list|(
name|namespaceURI
argument_list|,
name|qualifiedName
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#createCDATASection(java.lang.String) 	 */
specifier|public
name|CDATASection
name|createCDATASection
parameter_list|(
name|String
name|data
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|createCDATASection
argument_list|(
name|data
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#createComment(java.lang.String) 	 */
specifier|public
name|Comment
name|createComment
parameter_list|(
name|String
name|data
parameter_list|)
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|createComment
argument_list|(
name|data
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#createDocumentFragment() 	 */
specifier|public
name|DocumentFragment
name|createDocumentFragment
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|createDocumentFragment
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#createElement(java.lang.String) 	 */
specifier|public
name|Element
name|createElement
parameter_list|(
name|String
name|tagName
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|createElement
argument_list|(
name|tagName
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#createElementNS(java.lang.String, java.lang.String) 	 */
specifier|public
name|Element
name|createElementNS
parameter_list|(
name|String
name|namespaceURI
parameter_list|,
name|String
name|qualifiedName
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|createElementNS
argument_list|(
name|namespaceURI
argument_list|,
name|qualifiedName
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#createEntityReference(java.lang.String) 	 */
specifier|public
name|EntityReference
name|createEntityReference
parameter_list|(
name|String
name|name
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|createEntityReference
argument_list|(
name|name
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#createProcessingInstruction(java.lang.String, java.lang.String) 	 */
specifier|public
name|ProcessingInstruction
name|createProcessingInstruction
parameter_list|(
name|String
name|target
parameter_list|,
name|String
name|data
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|createProcessingInstruction
argument_list|(
name|target
argument_list|,
name|data
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#createTextNode(java.lang.String) 	 */
specifier|public
name|Text
name|createTextNode
parameter_list|(
name|String
name|data
parameter_list|)
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|createTextNode
argument_list|(
name|data
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getDoctype() 	 */
specifier|public
name|DocumentType
name|getDoctype
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getDoctype
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getDocumentElement() 	 */
specifier|public
name|Element
name|getDocumentElement
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getDocumentElement
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getDocumentURI() 	 */
specifier|public
name|String
name|getDocumentURI
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getDocumentURI
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getDomConfig() 	 */
specifier|public
name|DOMConfiguration
name|getDomConfig
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getDomConfig
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getElementById(java.lang.String) 	 */
specifier|public
name|Element
name|getElementById
parameter_list|(
name|String
name|elementId
parameter_list|)
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getElementById
argument_list|(
name|elementId
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getElementsByTagName(java.lang.String) 	 */
specifier|public
name|NodeList
name|getElementsByTagName
parameter_list|(
name|String
name|tagname
parameter_list|)
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getElementsByTagName
argument_list|(
name|tagname
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getElementsByTagNameNS(java.lang.String, java.lang.String) 	 */
specifier|public
name|NodeList
name|getElementsByTagNameNS
parameter_list|(
name|String
name|namespaceURI
parameter_list|,
name|String
name|localName
parameter_list|)
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getElementsByTagNameNS
argument_list|(
name|namespaceURI
argument_list|,
name|localName
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getImplementation() 	 */
specifier|public
name|DOMImplementation
name|getImplementation
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getImplementation
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getInputEncoding() 	 */
specifier|public
name|String
name|getInputEncoding
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getInputEncoding
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getStrictErrorChecking() 	 */
specifier|public
name|boolean
name|getStrictErrorChecking
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getStrictErrorChecking
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getXmlEncoding() 	 */
specifier|public
name|String
name|getXmlEncoding
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getXmlEncoding
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getXmlStandalone() 	 */
specifier|public
name|boolean
name|getXmlStandalone
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getXmlStandalone
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#getXmlVersion() 	 */
specifier|public
name|String
name|getXmlVersion
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getXmlVersion
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#importNode(org.w3c.dom.Node, boolean) 	 */
specifier|public
name|Node
name|importNode
parameter_list|(
name|Node
name|importedNode
parameter_list|,
name|boolean
name|deep
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|importNode
argument_list|(
name|importedNode
argument_list|,
name|deep
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#normalizeDocument() 	 */
specifier|public
name|void
name|normalizeDocument
parameter_list|()
block|{
name|getProxyObject
argument_list|()
operator|.
name|normalizeDocument
argument_list|()
expr_stmt|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#renameNode(org.w3c.dom.Node, java.lang.String, java.lang.String) 	 */
specifier|public
name|Node
name|renameNode
parameter_list|(
name|Node
name|n
parameter_list|,
name|String
name|namespaceURI
parameter_list|,
name|String
name|qualifiedName
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|renameNode
argument_list|(
name|n
argument_list|,
name|namespaceURI
argument_list|,
name|qualifiedName
argument_list|)
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#setDocumentURI(java.lang.String) 	 */
specifier|public
name|void
name|setDocumentURI
parameter_list|(
name|String
name|documentURI
parameter_list|)
block|{
name|getProxyObject
argument_list|()
operator|.
name|setDocumentURI
argument_list|(
name|documentURI
argument_list|)
expr_stmt|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#setStrictErrorChecking(boolean) 	 */
specifier|public
name|void
name|setStrictErrorChecking
parameter_list|(
name|boolean
name|strictErrorChecking
parameter_list|)
block|{
name|getProxyObject
argument_list|()
operator|.
name|setStrictErrorChecking
argument_list|(
name|strictErrorChecking
argument_list|)
expr_stmt|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#setXmlStandalone(boolean) 	 */
specifier|public
name|void
name|setXmlStandalone
parameter_list|(
name|boolean
name|xmlStandalone
parameter_list|)
throws|throws
name|DOMException
block|{
name|getProxyObject
argument_list|()
operator|.
name|setXmlStandalone
argument_list|(
name|xmlStandalone
argument_list|)
expr_stmt|;
block|}
comment|/* (non-Javadoc) 	 * @see org.w3c.dom.Document#setXmlVersion(java.lang.String) 	 */
specifier|public
name|void
name|setXmlVersion
parameter_list|(
name|String
name|xmlVersion
parameter_list|)
throws|throws
name|DOMException
block|{
name|getProxyObject
argument_list|()
operator|.
name|setXmlVersion
argument_list|(
name|xmlVersion
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|E
name|getProxyObject
parameter_list|()
block|{
return|return
name|document
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|setProxyObject
parameter_list|(
name|E
name|object
parameter_list|)
block|{
comment|//if (object instanceof DocumentAtExist) {
name|document
operator|=
operator|(
name|E
operator|)
name|object
expr_stmt|;
name|super
operator|.
name|setProxyObject
argument_list|(
name|document
argument_list|)
expr_stmt|;
comment|//} else
comment|//throw new IllegalArgumentException("Only DocumentAtExist allowed");
block|}
specifier|public
name|NodeAtExist
name|getNode
parameter_list|(
name|int
name|nodeNr
parameter_list|)
throws|throws
name|DOMException
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getNode
argument_list|(
name|nodeNr
argument_list|)
return|;
block|}
specifier|public
name|boolean
name|hasReferenceNodes
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|hasReferenceNodes
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|XmldbURI
name|getURI
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getURI
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|int
name|getDocId
parameter_list|()
block|{
return|return
name|getProxyObject
argument_list|()
operator|.
name|getDocId
argument_list|()
return|;
block|}
block|}
end_class

end_unit

