language: java

dist: xenial

services:
  - docker

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: oraclejdk11

    - os: osx
      osx_image: xcode9.3
      env: JAVA_HOME=$(/usr/libexec/java_home)


# TODO: DP switch tag to 'release' when merging into develop, not before!
deploy:
  provider: script
  skip_cleanup: true
  on:
    jdk: openjdk8
    branch: master
  #  before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # see https://github.com/travis-ci/dpl/issues/673
  script: >-
    cd exist-docker &&
    mvn -DskipTests -Ddocker.tag=experimental -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:build docker:push &&
    cd ..


cache:
  directories:
  - $HOME/.m2

# avoid 10k lines log limit
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Ddocker=true -B -V -q

script: mvn -DskipTests -Ddocker=true -q clean package

after_failure:
   - tar -cjf surefire-reports.tar.bz2 exist-core/target/surefire-reports
   - curl -v -u $CHUNK_USER:$CHUNK_PW -sT surefire-reports.tar.bz2 chunk.io

notifications:
  slack: exist-db:IXzUdqA0n11cnxaDz43ZQgdX
