notifications:
  hipchat: ec8fcfa661addc56a361a8ef536320@integrations

language: java

matrix:
  include:
    - jdk: openjdk8
    - jdk: oraclejdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: oraclejdk11

    - os: osx
      osx_image: xcode9.2
      env: JAVA_HOME=$(/usr/libexec/java_home)

script: ./build.sh -Dexist.autodeploy=off -Dtest.haltonerror=true -Dtest.haltonfailure=true clean clean-all all test

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2

after_failure:
   - tar -cf logs.zip test/junit/data
   - curl -u $CHUNK_USER:$CHUNK_PW -sT logs.zip chunk.io
