language: java

dist: xenial

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: oraclejdk11

    - os: osx
      osx_image: xcode9.3
      env: JAVA_HOME=$(/usr/libexec/java_home)

cache:
  directories:
  - $HOME/.m2

# temporary prerequisites
before_install:
   - git clone --single-branch --branch adam-custom-build https://github.com/adamretter/appassembler.git /tmp/appassembler
   - cd /tmp/appassembler
   - mvn clean install -DskipTests
   - git clone --single-branch --branch feature/redirect-file-name https://github.com/adamretter/maven-download-plugin.git /tmp/maven-download-plugin
   - cd /tmp/maven-download-plugin
   - mvn clean install -DskipTests
   - cd $TRAVIS_BUILD_DIR

after_failure:
   - tar -cjf surefire-reports.tar.bz2 exist-core/target/surefire-reports
   - curl -v -u $CHUNK_USER:$CHUNK_PW -sT surefire-reports.tar.bz2 chunk.io

notifications:
  slack: exist-db:IXzUdqA0n11cnxaDz43ZQgdX
