language: java

dist: bionic

# NOTE: To speed up multiple builds - Docker container is only built on JDK8, dependency checks also only happen on JDK8

matrix:
  include:

    - jdk: openjdk8
      env:
        - BUILD_DOCKER=true
        - MAVEN_OPTS="-Ddependency-check.skip=false"
      services:
        - docker

    - jdk: openjdk11
      env:
        - BUILD_DOCKER=false
        - MAVEN_OPTS="-Ddependency-check.skip=true"

    - jdk: openjdk14
      env:
        - BUILD_DOCKER=false
        - MAVEN_OPTS="-Ddependency-check.skip=true"

    - os: osx
      osx_image: xcode9.3
      env:
        - JAVA_HOME=$(/usr/libexec/java_home)
        - BUILD_DOCKER=false
        - MAVEN_OPTS="-Ddependency-check.skip=true"

cache:
  directories:
  - $HOME/.m2

install: travis_wait mvn -T 2C --strict-checksums -DskipTests=true -Dmaven.javadoc.skip=true -Ddocker=$BUILD_DOCKER install -B -V -q

script: mvn -T 2C -Ddocker=$BUILD_DOCKER test -B

after_failure:
   - tar -cjf surefire-reports.tar.bz2 exist-core/target/surefire-reports exist-core/target/test-logs-*
   - curl -v -u $CHUNK_USER:$CHUNK_PW -sT surefire-reports.tar.bz2 chunk.io

deploy:

  # Build and publish Docker Image for Docker tag `release` from updates to Git `master` branch with JDK8
  - provider: script
    cleanup: false
    on:
      jdk: openjdk8
      branch: master
    script: >-
      cd exist-docker &&
      mvn -DskipTests -Ddocker.tag=release -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:build docker:push &&
      cd ..


  # Build and publish Docker Image for Docker tag `latest` from updates to Git `develop` branch with JDK8
  - provider: script
    cleanup: false
    on:
      jdk: openjdk8
      branch: develop
    script: >-
      cd exist-docker &&
      mvn -DskipTests -Ddocker.tag=latest -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:build docker:push &&
      cd ..


notifications:
  slack: exist-db:$SLACK_TOKEN
