version: '{branch}-{build}'
install:
- cmd: set EXIST_HOME=%APPVEYOR_BUILD_FOLDER%
build_script:
- cmd: build.bat
test_script:
- cmd: build.bat -Dexist.autodeploy=off -Dtest.haltonerror=true -Dtest.haltonfailure=true travis
