version: '{branch}-{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk11
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

# temporary prerequisites
install:
   - cmd: git clone --single-branch --branch adam-custom-build https://github.com/adamretter/appassembler.git C:\Users\appveyor\AppData\Local\Temp\appassembler && cd C:\Users\appveyor\AppData\Local\Temp\appassembler && mvn clean install -DskipTests
   - cmd: git clone --single-branch --branch feature/redirect-file-name https://github.com/adamretter/maven-download-plugin.git C:\Users\appveyor\AppData\Local\Temp\maven-download-plugin && cd C:\Users\appveyor\AppData\Local\Temp\maven-download-plugin && mvn clean install -DskipTests
   - cmd: cd %APPVEYOR_BUILD_FOLDER%
   - sh: git clone --single-branch --branch adam-custom-build https://github.com/adamretter/appassembler.git /tmp/appassembler && cd /tmp/appassembler && mvn clean install -DskipTests
   - sh: git clone --single-branch --branch feature/redirect-file-name https://github.com/adamretter/maven-download-plugin.git /tmp/maven-download-plugin && cd /tmp/maven-download-plugin && mvn clean install -DskipTests
   - sh: cd $APPVEYOR_BUILD_FOLDER

build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

test_script:
  - mvn test -B

after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      foreach ($file in Get-ChildItem -Path "$($env:APPVEYOR_BUILD_FOLDER)\exist-core\target\surefire-reports\" -Filter *.xml) {
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $file.FullName)
      }

on_failure:
  - cmd: 7z a surefire-failed-data.zip %APPVEYOR_BUILD_FOLDER%\exist-core\target\surefire-reports\ && appveyor PushArtifact surefire-failed-data.zip
  - sh: tar czvf surefire-failed-data.tgz $APPVEYOR_BUILD_FOLDER/exist-core/target/surefire-reports/ && appveyor PushArtifact surefire-failed-data.tgz

artifacts:
  - path: exist-core\target\surefire-reports
    name: surefire-reports

cache:
  - C:\Users\appveyor\.m2
  - /home/appveyor/.m2

