version: '{branch}-{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk11
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

# use -q to avoid 10k lines log limit
build_script:
  - mvn -T 1.5C -DskipTests=true -Dmaven.javadoc.skip=true -Ddocker=true install -B -V -q

test_script:
  - mvn -T 1.5C -Ddocker=true test -B

after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      foreach ($file in Get-ChildItem -Path "$($env:APPVEYOR_BUILD_FOLDER)\exist-core\target\surefire-reports\" -Filter *.xml) {
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $file.FullName)
      }

on_failure:
  - cmd: 7z a surefire-failed-data.zip %APPVEYOR_BUILD_FOLDER%\exist-core\target\surefire-reports\ && appveyor PushArtifact surefire-failed-data.zip
  - sh: tar czvf surefire-failed-data.tgz $APPVEYOR_BUILD_FOLDER/exist-core/target/surefire-reports/ && appveyor PushArtifact surefire-failed-data.tgz

artifacts:
  - path: exist-core\target\surefire-reports
    name: surefire-reports
  - path: exist-core\target\test-logs
    name: test-logs

cache:
  - C:\Users\appveyor\.m2
  - /home/appveyor/.m2

