begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * ====================================================================  * Copyright (c) 2004-2010 TMate Software Ltd.  All rights reserved.  *  * This software is licensed as described in the file COPYING, which  * you should have received as part of this distribution.  The terms  * are also available at http://svnkit.com/license.html  * If newer versions of this license are posted there, you may use a  * newer version instead, at your option.  * ====================================================================  */
end_comment

begin_package
package|package
name|org
operator|.
name|exist
operator|.
name|versioning
operator|.
name|svn
operator|.
name|internal
operator|.
name|wc
package|;
end_package

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|versioning
operator|.
name|svn
operator|.
name|internal
operator|.
name|wc
operator|.
name|admin
operator|.
name|ISVNEntryHandler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|versioning
operator|.
name|svn
operator|.
name|internal
operator|.
name|wc
operator|.
name|admin
operator|.
name|SVNAdminArea
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|versioning
operator|.
name|svn
operator|.
name|internal
operator|.
name|wc
operator|.
name|admin
operator|.
name|SVNEntry
import|;
end_import

begin_import
import|import
name|org
operator|.
name|tmatesoft
operator|.
name|svn
operator|.
name|core
operator|.
name|SVNDepth
import|;
end_import

begin_import
import|import
name|org
operator|.
name|tmatesoft
operator|.
name|svn
operator|.
name|core
operator|.
name|SVNException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|tmatesoft
operator|.
name|svn
operator|.
name|core
operator|.
name|SVNMergeRange
import|;
end_import

begin_import
import|import
name|org
operator|.
name|tmatesoft
operator|.
name|svn
operator|.
name|core
operator|.
name|SVNURL
import|;
end_import

begin_import
import|import
name|org
operator|.
name|tmatesoft
operator|.
name|svn
operator|.
name|core
operator|.
name|internal
operator|.
name|wc
operator|.
name|ISVNReusableEditor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|tmatesoft
operator|.
name|svn
operator|.
name|core
operator|.
name|io
operator|.
name|SVNRepository
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_comment
comment|/**  * The<b>ISVNMergeStrategy</b> interface defines a number of methods  * to be used for directories merging.  *<p/>  * Alternative implementation is extended merge feature, it tracks  * copied and moved files to apply appropriate deltas to them.  *<p/>  * See svnkit-ext package  *  * @author TMate Software Ltd.  * @version 1.3  */
end_comment

begin_interface
specifier|public
interface|interface
name|ISVNMergeStrategy
block|{
name|ISVNReusableEditor
name|getMergeReportEditor
parameter_list|(
name|long
name|defaultStart
parameter_list|,
name|long
name|revision
parameter_list|,
name|SVNAdminArea
name|adminArea
parameter_list|,
name|SVNDepth
name|depth
parameter_list|,
name|AbstractDiffCallback
name|mergeCallback
parameter_list|,
name|ISVNReusableEditor
name|editor
parameter_list|)
throws|throws
name|SVNException
function_decl|;
name|ISVNReusableEditor
name|driveMergeReportEditor
parameter_list|(
name|File
name|targetWCPath
parameter_list|,
name|SVNURL
name|url1
parameter_list|,
name|long
name|revision1
parameter_list|,
name|SVNURL
name|url2
parameter_list|,
name|long
name|revision2
parameter_list|,
name|List
name|childrenWithMergeInfo
parameter_list|,
name|boolean
name|isRollBack
parameter_list|,
name|SVNDepth
name|depth
parameter_list|,
name|SVNAdminArea
name|adminArea
parameter_list|,
name|SVNMergeCallback
name|mergeCallback
parameter_list|,
name|ISVNReusableEditor
name|editor
parameter_list|)
throws|throws
name|SVNException
function_decl|;
name|ISVNEntryHandler
name|getMergeInfoEntryHandler
parameter_list|(
name|String
name|mergeSrcPath
parameter_list|,
name|SVNURL
name|sourceRootURL
parameter_list|,
name|long
name|revision1
parameter_list|,
name|long
name|revision2
parameter_list|,
name|SVNRepository
name|repository
parameter_list|,
name|SVNDepth
name|depth
parameter_list|,
name|List
name|childrenWithMergeInfo
parameter_list|)
function_decl|;
name|boolean
name|isRecordMergeInfo
parameter_list|()
function_decl|;
name|Object
index|[]
name|calculateRemainingRangeList
parameter_list|(
name|File
name|targetFile
parameter_list|,
name|SVNEntry
name|entry
parameter_list|,
name|SVNURL
name|sourceRoot
parameter_list|,
name|boolean
index|[]
name|indirect
parameter_list|,
name|SVNURL
name|url1
parameter_list|,
name|long
name|revision1
parameter_list|,
name|SVNURL
name|url2
parameter_list|,
name|long
name|revision2
parameter_list|,
name|SVNMergeRange
name|range
parameter_list|)
throws|throws
name|SVNException
function_decl|;
name|Map
name|calculateImplicitMergeInfo
parameter_list|(
name|SVNRepository
name|repos
parameter_list|,
name|SVNURL
name|url
parameter_list|,
name|long
index|[]
name|targetRev
parameter_list|,
name|long
name|start
parameter_list|,
name|long
name|end
parameter_list|)
throws|throws
name|SVNException
function_decl|;
block|}
end_interface

end_unit

