begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * eXist Open Source Native XML Database  * Copyright (C) 2003 The eXist Project  * http://exist-db.org  *  * This program is free software; you can redistribute it and/or  * modify it under the terms of the GNU Lesser General Public License  * as published by the Free Software Foundation; either version 2  * of the License, or (at your option) any later version.  *    * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU Lesser General Public License for more details.  *   * You should have received a copy of the GNU Lesser General Public License  * along with this program; if not, write to the Free Software Foundation  * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.  *    *  $Id$  */
end_comment

begin_package
package|package
name|org
operator|.
name|exist
operator|.
name|xquery
package|;
end_package

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|dom
operator|.
name|NodeProxy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|dom
operator|.
name|QName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|xquery
operator|.
name|util
operator|.
name|ExpressionDumper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|xquery
operator|.
name|value
operator|.
name|Type
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Node
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|stream
operator|.
name|XMLStreamReader
import|;
end_import

begin_comment
comment|/**  * The class<code>AnyNodeTest</code>  *  * @author Wolfgang Meier (wolfgang@exist-db.org)  *  */
end_comment

begin_class
specifier|public
class|class
name|AnyNodeTest
implements|implements
name|NodeTest
block|{
comment|/* (non-Javadoc)      * @see org.exist.xquery.NodeTest#getName()      */
specifier|public
name|QName
name|getName
parameter_list|()
block|{
return|return
literal|null
return|;
block|}
comment|/* (non-Javadoc)      * @see org.exist.xquery.NodeTest#isWildcardTest()      */
specifier|public
name|boolean
name|isWildcardTest
parameter_list|()
block|{
return|return
literal|true
return|;
block|}
comment|/* (non-Javadoc)      * @see org.exist.xquery.NodeTest#matches(org.w3c.dom.Node)      */
specifier|public
name|boolean
name|matches
parameter_list|(
name|Node
name|node
parameter_list|)
block|{
return|return
operator|(
name|node
operator|.
name|getNodeType
argument_list|()
operator|!=
name|Node
operator|.
name|ATTRIBUTE_NODE
operator|)
return|;
block|}
comment|/* (non-Javadoc)      * @see org.exist.xquery.NodeTest#matches(org.exist.dom.NodeProxy)      */
specifier|public
name|boolean
name|matches
parameter_list|(
name|NodeProxy
name|proxy
parameter_list|)
block|{
name|int
name|type
init|=
name|proxy
operator|.
name|getType
argument_list|()
decl_stmt|;
if|if
condition|(
name|type
operator|==
name|Type
operator|.
name|ITEM
operator|||
name|type
operator|==
name|Type
operator|.
name|NODE
condition|)
block|{
if|if
condition|(
name|proxy
operator|.
name|getNodeType
argument_list|()
operator|!=
name|NodeProxy
operator|.
name|UNKNOWN_NODE_TYPE
condition|)
block|{
return|return
name|matches
argument_list|(
name|proxy
operator|.
name|getNode
argument_list|()
argument_list|)
return|;
block|}
return|return
name|proxy
operator|.
name|getNodeType
argument_list|()
operator|!=
name|Node
operator|.
name|ATTRIBUTE_NODE
return|;
block|}
if|else if
condition|(
name|type
operator|==
name|Type
operator|.
name|ATTRIBUTE
operator|&&
name|proxy
operator|.
name|getNodeType
argument_list|()
operator|==
name|Node
operator|.
name|ATTRIBUTE_NODE
condition|)
block|{
return|return
literal|true
return|;
block|}
else|else
block|{
return|return
name|type
operator|!=
name|Node
operator|.
name|ATTRIBUTE_NODE
return|;
block|}
block|}
specifier|public
name|boolean
name|matches
parameter_list|(
name|XMLStreamReader
name|reader
parameter_list|)
block|{
return|return
name|reader
operator|.
name|getEventType
argument_list|()
operator|!=
name|XMLStreamReader
operator|.
name|ATTRIBUTE
return|;
block|}
specifier|public
name|boolean
name|matches
parameter_list|(
name|QName
name|name
parameter_list|)
block|{
return|return
literal|false
return|;
block|}
specifier|public
name|void
name|dump
parameter_list|(
name|ExpressionDumper
name|dumper
parameter_list|)
block|{
if|if
condition|(
name|dumper
operator|.
name|verbosity
argument_list|()
operator|>
literal|1
condition|)
block|{
name|dumper
operator|.
name|display
argument_list|(
literal|"node()"
argument_list|)
expr_stmt|;
block|}
block|}
comment|/* (non-Javadoc)      * @see java.lang.Object#toString()      */
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
literal|"node()"
return|;
block|}
comment|/* (non-Javadoc)      * @see org.exist.xquery.NodeTest#setType(int)      */
specifier|public
name|void
name|setType
parameter_list|(
name|int
name|nodeType
parameter_list|)
block|{
comment|//Nothing to do
block|}
specifier|public
name|int
name|getType
parameter_list|()
block|{
return|return
name|Type
operator|.
name|NODE
return|;
block|}
block|}
end_class

end_unit

