begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/* eXist Native XML Database  * Copyright (C) 2000-03,  Wolfgang M. Meier (wolfgang@exist-db.org)  *  * This library is free software; you can redistribute it and/or  * modify it under the terms of the GNU Library General Public License  * as published by the Free Software Foundation; either version 2  * of the License, or (at your option) any later version.  *  * This library is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU Library General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.  *   * $Id$  */
end_comment

begin_package
package|package
name|org
operator|.
name|exist
operator|.
name|xquery
package|;
end_package

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|xquery
operator|.
name|util
operator|.
name|ExpressionDumper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|xquery
operator|.
name|value
operator|.
name|AtomicValue
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|xquery
operator|.
name|value
operator|.
name|Item
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|xquery
operator|.
name|value
operator|.
name|Sequence
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|xquery
operator|.
name|value
operator|.
name|SequenceIterator
import|;
end_import

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|xquery
operator|.
name|value
operator|.
name|StringValue
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Iterator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_comment
comment|/**  * Node constructor for attribute nodes.  *   * @author wolf  */
end_comment

begin_class
specifier|public
class|class
name|AttributeConstructor
extends|extends
name|NodeConstructor
block|{
specifier|final
name|String
name|qname
decl_stmt|;
specifier|public
specifier|final
name|List
argument_list|<
name|Object
argument_list|>
name|contents
init|=
operator|new
name|ArrayList
argument_list|<
name|Object
argument_list|>
argument_list|(
literal|5
argument_list|)
decl_stmt|;
name|boolean
name|isNamespaceDecl
init|=
literal|false
decl_stmt|;
specifier|public
name|AttributeConstructor
parameter_list|(
name|XQueryContext
name|context
parameter_list|,
name|String
name|name
parameter_list|)
block|{
name|super
argument_list|(
name|context
argument_list|)
expr_stmt|;
if|if
condition|(
name|name
operator|.
name|startsWith
argument_list|(
literal|"xmlns"
argument_list|)
condition|)
name|isNamespaceDecl
operator|=
literal|true
expr_stmt|;
name|this
operator|.
name|qname
operator|=
name|name
expr_stmt|;
block|}
specifier|public
name|void
name|addValue
parameter_list|(
name|String
name|value
parameter_list|)
block|{
name|contents
operator|.
name|add
argument_list|(
name|value
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|addEnclosedExpr
parameter_list|(
name|Expression
name|expr
parameter_list|)
throws|throws
name|XPathException
block|{
if|if
condition|(
name|isNamespaceDecl
condition|)
throw|throw
operator|new
name|XPathException
argument_list|(
name|this
argument_list|,
literal|"enclosed expressions are not allowed in namespace "
operator|+
literal|"declaration attributes"
argument_list|)
throw|;
name|contents
operator|.
name|add
argument_list|(
name|expr
argument_list|)
expr_stmt|;
block|}
specifier|public
name|String
name|getQName
parameter_list|()
block|{
return|return
name|qname
return|;
block|}
specifier|public
name|boolean
name|isNamespaceDeclaration
parameter_list|()
block|{
return|return
name|isNamespaceDecl
return|;
block|}
comment|/* (non-Javadoc)      * @see org.exist.xquery.Expression#analyze(org.exist.xquery.Expression)      */
specifier|public
name|void
name|analyze
parameter_list|(
name|AnalyzeContextInfo
name|contextInfo
parameter_list|)
throws|throws
name|XPathException
block|{
name|super
operator|.
name|analyze
argument_list|(
name|contextInfo
argument_list|)
expr_stmt|;
name|contextInfo
operator|.
name|setParent
argument_list|(
name|this
argument_list|)
expr_stmt|;
for|for
control|(
name|Object
name|next
range|:
name|contents
control|)
block|{
if|if
condition|(
name|next
operator|instanceof
name|Expression
condition|)
operator|(
operator|(
name|Expression
operator|)
name|next
operator|)
operator|.
name|analyze
argument_list|(
name|contextInfo
argument_list|)
expr_stmt|;
block|}
block|}
comment|/* (non-Javadoc) 	 * @see org.exist.xquery.Expression#eval(org.exist.xquery.StaticContext, org.exist.dom.DocumentSet, org.exist.xquery.value.Sequence, org.exist.xquery.value.Item) 	 */
specifier|public
name|Sequence
name|eval
parameter_list|(
name|Sequence
name|contextSequence
parameter_list|,
name|Item
name|contextItem
parameter_list|)
throws|throws
name|XPathException
block|{
name|StringBuilder
name|buf
init|=
operator|new
name|StringBuilder
argument_list|()
decl_stmt|;
for|for
control|(
name|Object
name|next
range|:
name|contents
control|)
block|{
if|if
condition|(
name|next
operator|instanceof
name|Expression
condition|)
name|evalEnclosedExpr
argument_list|(
operator|(
operator|(
name|Expression
operator|)
name|next
operator|)
operator|.
name|eval
argument_list|(
name|contextSequence
argument_list|,
name|contextItem
argument_list|)
argument_list|,
name|buf
argument_list|)
expr_stmt|;
else|else
name|buf
operator|.
name|append
argument_list|(
name|next
argument_list|)
expr_stmt|;
block|}
comment|//TODO : include that tricky attribute normalization here
name|StringValue
name|result
init|=
operator|new
name|StringValue
argument_list|(
name|buf
operator|.
name|toString
argument_list|()
argument_list|)
decl_stmt|;
comment|// String values as expressions are already expanded by
comment|// the parser -- Alex
comment|//result.expand();
return|return
name|result
return|;
block|}
specifier|private
name|void
name|evalEnclosedExpr
parameter_list|(
name|Sequence
name|seq
parameter_list|,
name|StringBuilder
name|buf
parameter_list|)
throws|throws
name|XPathException
block|{
name|Item
name|item
decl_stmt|;
name|AtomicValue
name|atomic
decl_stmt|;
for|for
control|(
name|SequenceIterator
name|i
init|=
name|seq
operator|.
name|iterate
argument_list|()
init|;
name|i
operator|.
name|hasNext
argument_list|()
condition|;
control|)
block|{
name|item
operator|=
name|i
operator|.
name|nextItem
argument_list|()
expr_stmt|;
name|atomic
operator|=
name|item
operator|.
name|atomize
argument_list|()
expr_stmt|;
name|buf
operator|.
name|append
argument_list|(
name|atomic
operator|.
name|getStringValue
argument_list|()
argument_list|)
expr_stmt|;
if|if
condition|(
name|i
operator|.
name|hasNext
argument_list|()
condition|)
name|buf
operator|.
name|append
argument_list|(
literal|' '
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** 	 * If this is a namespace declaration attribute, return 	 * the single string value of the attribute. 	 */
specifier|public
name|String
name|getLiteralValue
parameter_list|()
block|{
if|if
condition|(
name|contents
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
return|return
literal|""
return|;
return|return
operator|(
name|String
operator|)
name|contents
operator|.
name|get
argument_list|(
literal|0
argument_list|)
return|;
block|}
comment|/* (non-Javadoc)      * @see org.exist.xquery.Expression#dump(org.exist.xquery.util.ExpressionDumper)      */
specifier|public
name|void
name|dump
parameter_list|(
name|ExpressionDumper
name|dumper
parameter_list|)
block|{
name|dumper
operator|.
name|display
argument_list|(
literal|"attribute "
argument_list|)
expr_stmt|;
comment|//TODO : remove curly braces if Qname
name|dumper
operator|.
name|display
argument_list|(
literal|"{"
argument_list|)
expr_stmt|;
name|dumper
operator|.
name|display
argument_list|(
name|qname
argument_list|)
expr_stmt|;
name|dumper
operator|.
name|display
argument_list|(
literal|"} "
argument_list|)
expr_stmt|;
name|dumper
operator|.
name|display
argument_list|(
literal|"{"
argument_list|)
expr_stmt|;
name|dumper
operator|.
name|startIndent
argument_list|()
expr_stmt|;
for|for
control|(
name|Object
name|next
range|:
name|contents
control|)
block|{
if|if
condition|(
name|next
operator|instanceof
name|Expression
condition|)
operator|(
operator|(
name|Expression
operator|)
name|next
operator|)
operator|.
name|dump
argument_list|(
name|dumper
argument_list|)
expr_stmt|;
else|else
name|dumper
operator|.
name|display
argument_list|(
name|next
argument_list|)
expr_stmt|;
block|}
name|dumper
operator|.
name|endIndent
argument_list|()
expr_stmt|;
name|dumper
operator|.
name|nl
argument_list|()
operator|.
name|display
argument_list|(
literal|"} "
argument_list|)
expr_stmt|;
block|}
specifier|public
name|String
name|toString
parameter_list|()
block|{
name|StringBuilder
name|result
init|=
operator|new
name|StringBuilder
argument_list|()
decl_stmt|;
name|result
operator|.
name|append
argument_list|(
literal|"attribute "
argument_list|)
expr_stmt|;
comment|//TODO : remove curly braces if Qname
name|result
operator|.
name|append
argument_list|(
literal|"{"
argument_list|)
expr_stmt|;
name|result
operator|.
name|append
argument_list|(
name|qname
argument_list|)
expr_stmt|;
name|result
operator|.
name|append
argument_list|(
literal|"} "
argument_list|)
expr_stmt|;
name|result
operator|.
name|append
argument_list|(
literal|"{"
argument_list|)
expr_stmt|;
for|for
control|(
name|Object
name|next
range|:
name|contents
control|)
block|{
if|if
condition|(
name|next
operator|instanceof
name|Expression
condition|)
name|result
operator|.
name|append
argument_list|(
name|next
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
else|else
name|result
operator|.
name|append
argument_list|(
name|next
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|result
operator|.
name|append
argument_list|(
literal|"} "
argument_list|)
expr_stmt|;
return|return
name|result
operator|.
name|toString
argument_list|()
return|;
block|}
comment|/* (non-Javadoc) 	 * @see org.exist.xquery.NodeConstructor#resetState() 	 */
annotation|@
name|Override
specifier|public
name|void
name|resetState
parameter_list|(
name|boolean
name|postOptimization
parameter_list|)
block|{
name|super
operator|.
name|resetState
argument_list|(
name|postOptimization
argument_list|)
expr_stmt|;
for|for
control|(
name|Object
name|object
range|:
name|contents
control|)
block|{
if|if
condition|(
name|object
operator|instanceof
name|Expression
condition|)
operator|(
operator|(
name|Expression
operator|)
name|object
operator|)
operator|.
name|resetState
argument_list|(
name|postOptimization
argument_list|)
expr_stmt|;
block|}
block|}
specifier|public
name|Iterator
argument_list|<
name|Object
argument_list|>
name|contentIterator
parameter_list|()
block|{
return|return
name|contents
operator|.
name|iterator
argument_list|()
return|;
block|}
block|}
end_class

end_unit

