begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|//
end_comment

begin_comment
comment|// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
end_comment

begin_comment
comment|// See<a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
end_comment

begin_comment
comment|// Any modifications to this file will be lost upon recompilation of the source schema.
end_comment

begin_comment
comment|// Generated on: 2017.12.01 at 08:56:54 PM GMT
end_comment

begin_comment
comment|//
end_comment

begin_package
package|package
name|org
operator|.
name|exist
operator|.
name|http
operator|.
name|jaxb
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlRegistry
import|;
end_import

begin_comment
comment|/**  * This object contains factory methods for each   * Java content interface and Java element interface   * generated in the org.exist.http.jaxb package.   * An ObjectFactory allows you to programatically  * construct new instances of the Java representation   * for XML content. The Java representation of XML   * content can consist of schema derived interfaces   * and classes representing the binding of schema   * type definitions, element declarations and model   * groups.  Factory methods for each of these are   * provided in this class.  *   */
end_comment

begin_class
annotation|@
name|XmlRegistry
specifier|public
class|class
name|ObjectFactory
block|{
comment|/**      * Create an instance of {@link Result }      *      * @return the result      */
specifier|public
name|Result
name|createResult
parameter_list|()
block|{
return|return
operator|new
name|Result
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link Query }      *      * @return the query      */
specifier|public
name|Query
name|createQuery
parameter_list|()
block|{
return|return
operator|new
name|Query
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link Sequence }      *      * @return the sequence      */
specifier|public
name|Sequence
name|createSequence
parameter_list|()
block|{
return|return
operator|new
name|Sequence
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link Query.Properties }      *      * @return the query properties      */
specifier|public
name|Query
operator|.
name|Properties
name|createQueryProperties
parameter_list|()
block|{
return|return
operator|new
name|Query
operator|.
name|Properties
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link Query.Variables }      *      * @return the query variables      */
specifier|public
name|Query
operator|.
name|Variables
name|createQueryVariables
parameter_list|()
block|{
return|return
operator|new
name|Query
operator|.
name|Variables
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link Query.Variables.Variable }      *      * @return the variable      */
specifier|public
name|Query
operator|.
name|Variables
operator|.
name|Variable
name|createQueryVariablesVariable
parameter_list|()
block|{
return|return
operator|new
name|Query
operator|.
name|Variables
operator|.
name|Variable
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link Collection }      *      * @return the collection      */
specifier|public
name|Collection
name|createCollection
parameter_list|()
block|{
return|return
operator|new
name|Collection
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link Result.Value }      *      * @return the result value      */
specifier|public
name|Result
operator|.
name|Value
name|createResultValue
parameter_list|()
block|{
return|return
operator|new
name|Result
operator|.
name|Value
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link Sequence.Value }      *      * @return the sequence value      */
specifier|public
name|Sequence
operator|.
name|Value
name|createSequenceValue
parameter_list|()
block|{
return|return
operator|new
name|Sequence
operator|.
name|Value
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link Query.Properties.Property }      *      * @return the property      */
specifier|public
name|Query
operator|.
name|Properties
operator|.
name|Property
name|createQueryPropertiesProperty
parameter_list|()
block|{
return|return
operator|new
name|Query
operator|.
name|Properties
operator|.
name|Property
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link Query.Variables.Variable.Qname }      *      * @return the qname      */
specifier|public
name|Query
operator|.
name|Variables
operator|.
name|Variable
operator|.
name|Qname
name|createQueryVariablesVariableQname
parameter_list|()
block|{
return|return
operator|new
name|Query
operator|.
name|Variables
operator|.
name|Variable
operator|.
name|Qname
argument_list|()
return|;
block|}
block|}
end_class

end_unit

