begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * eXist Open Source Native XML Database  * Copyright (C) 2001-2017 The eXist Project  * http://exist-db.org  *  * This program is free software; you can redistribute it and/or  * modify it under the terms of the GNU Lesser General Public License  * as published by the Free Software Foundation; either version 2  * of the License, or (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU Lesser General Public License for more details.  *  * You should have received a copy of the GNU Lesser General Public  * License along with this library; if not, write to the Free Software  * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA  */
end_comment

begin_package
package|package
name|org
operator|.
name|exist
operator|.
name|management
operator|.
name|impl
package|;
end_package

begin_import
import|import
name|org
operator|.
name|exist
operator|.
name|storage
operator|.
name|lock
operator|.
name|LockInfo
import|;
end_import

begin_comment
comment|/**  * Detail information about lock being held.  */
end_comment

begin_class
specifier|public
class|class
name|Lock
block|{
specifier|private
specifier|final
name|String
name|waitingThread
decl_stmt|;
specifier|private
specifier|final
name|String
name|lockType
decl_stmt|;
specifier|private
specifier|final
name|String
name|lockMode
decl_stmt|;
specifier|private
specifier|final
name|String
name|id
decl_stmt|;
specifier|private
specifier|final
name|String
index|[]
name|owner
decl_stmt|;
specifier|private
specifier|final
name|String
index|[]
name|waitingForRead
decl_stmt|;
specifier|private
specifier|final
name|String
index|[]
name|waitingForWrite
decl_stmt|;
specifier|public
name|Lock
parameter_list|(
name|String
name|waitingThread
parameter_list|,
name|LockInfo
name|info
parameter_list|)
block|{
name|this
operator|.
name|waitingThread
operator|=
name|waitingThread
expr_stmt|;
name|this
operator|.
name|lockType
operator|=
name|info
operator|.
name|getLockType
argument_list|()
expr_stmt|;
name|this
operator|.
name|lockMode
operator|=
name|info
operator|.
name|getLockMode
argument_list|()
expr_stmt|;
name|this
operator|.
name|id
operator|=
name|info
operator|.
name|getId
argument_list|()
expr_stmt|;
name|this
operator|.
name|owner
operator|=
name|info
operator|.
name|getOwners
argument_list|()
expr_stmt|;
name|this
operator|.
name|waitingForRead
operator|=
name|info
operator|.
name|getWaitingForRead
argument_list|()
expr_stmt|;
name|this
operator|.
name|waitingForWrite
operator|=
name|info
operator|.
name|getWaitingForWrite
argument_list|()
expr_stmt|;
block|}
specifier|public
name|String
name|getWaitingThread
parameter_list|()
block|{
return|return
name|waitingThread
return|;
block|}
specifier|public
name|String
name|getLockType
parameter_list|()
block|{
return|return
name|lockType
return|;
block|}
specifier|public
name|String
name|getLockMode
parameter_list|()
block|{
return|return
name|lockMode
return|;
block|}
specifier|public
name|String
name|getId
parameter_list|()
block|{
return|return
name|id
return|;
block|}
specifier|public
name|String
index|[]
name|getOwner
parameter_list|()
block|{
return|return
name|owner
return|;
block|}
specifier|public
name|String
index|[]
name|getWaitingForRead
parameter_list|()
block|{
return|return
name|waitingForRead
return|;
block|}
specifier|public
name|String
index|[]
name|getWaitingForWrite
parameter_list|()
block|{
return|return
name|waitingForWrite
return|;
block|}
block|}
end_class

end_unit

