begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|//$Id$
end_comment

begin_package
package|package
name|org
operator|.
name|exist
operator|.
name|cluster
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Vector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|log4j
operator|.
name|Logger
import|;
end_import

begin_comment
comment|/**  * Created by Francesco Mondora.  *  * @author Francesco Mondora aka Makkina  * @author Michele Danieli aka mdanieli  * @author Nicola Breda aka maiale  *         Date: 05-aug-2005  *         Time: 18.09.08  *         Revision $Revision$  */
end_comment

begin_class
specifier|public
class|class
name|ClusterChannel
block|{
annotation|@
name|SuppressWarnings
argument_list|(
literal|"unused"
argument_list|)
specifier|private
specifier|static
name|Logger
name|log
init|=
name|Logger
operator|.
name|getLogger
argument_list|(
name|ClusterChannel
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|public
specifier|static
specifier|final
name|String
name|EXIST_GROUP
init|=
literal|"exist-replication-group"
decl_stmt|;
specifier|public
specifier|static
name|Vector
argument_list|<
name|String
argument_list|>
name|incomingEvents
init|=
operator|new
name|Vector
argument_list|<
name|String
argument_list|>
argument_list|()
decl_stmt|;
specifier|public
specifier|static
name|boolean
name|hasToBePublished
parameter_list|(
name|String
name|event
parameter_list|)
block|{
return|return
operator|!
name|incomingEvents
operator|.
name|contains
argument_list|(
name|event
argument_list|)
return|;
block|}
specifier|public
specifier|static
name|void
name|accountEvent
parameter_list|(
name|String
name|event
parameter_list|)
block|{
name|incomingEvents
operator|.
name|addElement
argument_list|(
name|event
argument_list|)
expr_stmt|;
block|}
specifier|public
specifier|static
name|void
name|removeEvent
parameter_list|(
name|String
name|code
parameter_list|)
block|{
name|incomingEvents
operator|.
name|remove
argument_list|(
name|code
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

