begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|//$Id$
end_comment

begin_package
package|package
name|org
operator|.
name|exist
operator|.
name|cluster
package|;
end_package

begin_import
import|import
name|org
operator|.
name|xmldb
operator|.
name|api
operator|.
name|base
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|org
operator|.
name|xmldb
operator|.
name|api
operator|.
name|modules
operator|.
name|CollectionManagementService
import|;
end_import

begin_comment
comment|/**  * Created by Francesco Mondora.  *  * @author Francesco Mondora aka Makkina  *         Date: 14-dic-2004  *         Time: 18.21.12  *         Revision $Revision$  */
end_comment

begin_class
specifier|public
class|class
name|CreateCollectionClusterEvent
extends|extends
name|ClusterEvent
block|{
name|String
name|parent
decl_stmt|;
name|String
name|collectionName
decl_stmt|;
specifier|public
name|CreateCollectionClusterEvent
parameter_list|(
name|String
name|parent
parameter_list|,
name|String
name|collectionName
parameter_list|)
block|{
name|this
operator|.
name|parent
operator|=
name|parent
expr_stmt|;
name|this
operator|.
name|collectionName
operator|=
name|collectionName
expr_stmt|;
block|}
comment|/**      * Execute the current command.      */
specifier|public
name|void
name|execute
parameter_list|()
throws|throws
name|ClusterException
block|{
try|try
block|{
name|Collection
name|parent
init|=
name|getCollection
argument_list|(
name|this
operator|.
name|parent
argument_list|)
decl_stmt|;
name|CollectionManagementService
name|mgtService
init|=
operator|(
name|CollectionManagementService
operator|)
name|parent
operator|.
name|getService
argument_list|(
literal|"CollectionManagementService"
argument_list|,
literal|"1.0"
argument_list|)
decl_stmt|;
name|mgtService
operator|.
name|createCollection
argument_list|(
name|this
operator|.
name|collectionName
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
name|e
operator|.
name|printStackTrace
argument_list|()
expr_stmt|;
block|}
block|}
specifier|public
name|int
name|hashCode
parameter_list|()
block|{
return|return
name|this
operator|.
name|collectionName
operator|.
name|hashCode
argument_list|()
operator|^
name|this
operator|.
name|parent
operator|.
name|hashCode
argument_list|()
return|;
block|}
block|}
end_class

end_unit

